[modify] debian/opensbi-spacemit.postinst
* check /sys/devices/soc0/family and give an extra tip

Change-Id: I45dc68bcaf5996b2373aaa63708b511064c2cdeb

diff --git a/debian/opensbi-spacemit.postinst b/debian/opensbi-spacemit.postinst
--- a/debian/opensbi-spacemit.postinst
+++ b/debian/opensbi-spacemit.postinst
@@ -4,9 +4,11 @@ set -e
 case "$1" in
 configure)
     target=""
-    if grep -q '^spacemit' /sys/firmware/devicetree/base/model; then
+    if grep -q '^spacemit' /sys/firmware/devicetree/base/model || grep -q '^spacemit' /sys/devices/soc0/family; then
         target="spacemit"
     else
+        echo "Neither /sys/firmware/devicetree/base/model nor /sys/devices/soc0/family starts with 'spacemit'."
+        echo "This may indicate that you are installing this package in a chroot environment."
         exit 0
     fi
 
@@ -35,17 +37,27 @@ configure)
             ;;
         *)
             echo "Unsupported root=$ROOT"
-            exit 0
+            exit 1
             ;;
         esac
     else
         echo "Missing root= in cmdline"
-        exit 0
+        exit 1
     fi
 
-    if [ -n "$target" ] && [ -e $OPENSBI ]; then
-        dd if=/usr/lib/riscv64-linux-gnu/opensbi/generic/fw_dynamic.itb of=$OPENSBI seek=$OPENSBI_SEEK bs=1K && sync
-    fi
+    # 待检查文件/分区列表
+    files="/usr/lib/riscv64-linux-gnu/opensbi/generic/fw_dynamic.itb $OPENSBI"
+    for file in $files; do
+        if [ ! -e "$file" ]; then
+            # 任意不存在则退出
+            echo "Missing $file"
+            exit 1
+        fi
+    done
+
+    # 此前已经做了所有检查
+    dd if=/usr/lib/riscv64-linux-gnu/opensbi/generic/fw_dynamic.itb of=$OPENSBI seek=$OPENSBI_SEEK bs=1K && sync
+
     ;;
 esac
 
